# Generated by Django 3.0.7 on 2020-06-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prephd',
            name='Student_roll_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prephd',
            name='Registration_month',
            field=models.DateField(),
        ),
    ]
