# Generated by Django 3.0.7 on 2020-06-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0002_auto_20200604_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_roll_number', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('gender', models.CharField(choices=[('0', 'Permission Granted'), ('1', 'Permission Denied')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Plagarism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_roll_number', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('File_upload', models.FileField(upload_to='')),
            ],
        ),
    ]
