# Generated by Django 3.0.5 on 2020-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0003_extension_period_plagarism'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_of_supervisor_or_co_supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_roll_number', models.CharField(max_length=20)),
                ('Application_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Colloquium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_roll_number', models.CharField(max_length=20)),
                ('Submission_date', models.DateField()),
                ('Satisfaction', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Research_Methodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_roll_number', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Satisfaction', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=11)),
                ('Completed', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Revise_and_Resubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_roll_number', models.CharField(max_length=20)),
                ('Submission_date_of_revised_thesis', models.DateField()),
                ('Date_communicated_to_DE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RRM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_roll_number', models.CharField(max_length=20)),
                ('RRM_number', models.CharField(max_length=20)),
                ('Date_of_registration', models.DateField()),
                ('Satisfaction', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=11)),
                ('Marks_obtained', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Thesis_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_roll_number', models.CharField(max_length=20)),
                ('Student_submission_date', models.DateField()),
                ('Submission_date_to_DE', models.DateField()),
                ('Reviewing_reports_by_DE', models.DateField()),
                ('Date_of_communication_to_student', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Viva_Voca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_roll_number', models.CharField(max_length=20)),
                ('DE_intimation_date', models.DateField()),
                ('Final_dates', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='extension_period',
            old_name='gender',
            new_name='Permission',
        ),
    ]
